name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Format
        run: cargo +nightly fmt --check

  build_and_test:
    name: Build And Test (Rust ${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ["1.91", "1.92", "1.93", "1.94", "1.95"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build
      - name: Unit Tests
        run: cargo test

  clippy:
    name: Clippy
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.95"
          components: clippy
      - name: Clippy
        run: cargo clippy

  integration:
    name: Integration Tests
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: Run tests on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v4
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          compose: Fedora-latest
          tmt_plan_regex: adb
          create_issue_comment: true
          update_pull_request_status: true
          pull_request_status_name: Integration (adb)
